# image will be published to ghcr.io/<user>/<name>
name: ublue-kinoite-light
# description will be included in the image's metadata
description: Ublue kinoite minimal

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 39 # latest is also supported if you want new updates ASAP

# list of modules, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copy static configurations
                  # configuration you wish to end up in /etc/ on the booted system should be 
                  # added into /usr/etc/ as that is the proper "distro" config directory on ostree
                  # read more in the files module's README
  - type: rpm-ostree
    install:
      - podman
      - htop
    remove:
      - firefox # default firefox removed in favor of flatpak
      - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems
      - kf5-akonadi-server-mysql
      - kf5-akonadi-server
      - kmousetool
      - krfb-libs
      - krfb
      - mariadb-backup
      - mariadb-cracklib-password-check
      - mariadb-common
      - mariadb-server-utils
      - mariadb-server
      - mariadb-errmsg
      - mariadb-gssapi-server
      - mariadb
      - filelight
      - mariadb-connector-c
      - mariadb-connector-c-config
      - perl-DBD-MariaDB
      - qt5-qtbase-mysql
      - apr
      - apr-util
      - apr-util-openssl
      - apr-util-bdb
      - grub2-tools-extra
      - intel-media-driver
      - libva-intel-driver
      - nvtop
      - tmux
      - wireguard-tools
      - fzf
      - icoutils
      - kcron

  - type: default-flatpaks
    notify: true   # Send notification after install/uninstall is finished (true/false)
    #system:
      # If no repo information is specified, Flathub will be used by default
      #repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      #repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      #install:
      # - org.gnome.Loupe
      # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08).
      # Only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Multiple install of same flatpaks with different branches is not supported.
      #remove:
      # - org.gnome.eog
      #
    # A flatpak repo can also be added without having to install flatpaks,
    # as long as one of the repo- fields is present
    user:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      install:
        - org.mozilla.firefox
        - org.kde.kcalc
        - org.kde.gwenview
        - org.kde.okular
        - org.kde.filelight

  - type: bling # configure what to pull in from ublue-os/bling
    install:
      - ublue-update

  - type: systemd
    user:
      enabled:
        - podman.service
        - podman-auto-update.timer
    system:
      enabled:
        - ublue-update.timer

  - type: script
    scripts:
      # this sets up the proper policy & signing files for signed images to work
      - signing.sh
      - kinoite.sh