name: sync-fork
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Setup git (1/2)
        uses: actions/checkout@v4
      - name: Setup git (2/2)
        run: |
          git config user.name "Vietchinh GitHub Actions Bot"
          git config user.email "1348151+vietchinh@users.noreply.github.com"
      - name: Add ublue-os startingpoint remote
        run: git remote add template https://github.com/ublue-os/startingpoint
      - name: Fetch all
        run: git fetch --all
      - name: Checkout template
        run: git checkout origin/template
      - name: Check diff between template/template and template
        run: echo "DIFF_COUNT=`git diff --numstat --minimal template/template..template | cut -c1-1`" >> $GITHUB_ENV
      - name: Git merge changes from template to ubluelight/template
#        if: ${{ env.DIFF_COUNT != '' }}
        run: git merge template/template --allow-unrelated-histories && git push origin template
      - name: Checkout live
        run: git checkout live
      - name: Git rebase template in live
        run: git rebase --onto origin/template --root live && git push origin live -f