name: sync-fork
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout template
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.FORK_SYNC_TOKEN }}
          fetch-depth: 0
      - name: git setup
        run: |
          git config user.name "Vietchinh GitHub Actions Bot"
          git config user.email "1348151+vietchinh@users.noreply.github.com"
      - name: Add ublue-os startingpoint remote
        run: git remote add template https://github.com/ublue-os/startingpoint
      - name: Fetch all
        run: git fetch --all
      - name: Checkout template
        run: git checkout -b template --track origin/template
      - name: Check if there is an update available
        id: check
        run: |
          DIFF_COUNT=`git diff --numstat --minimal template/template..template | cut -c1-1`
          if [ -z "$DIFF_COUNT" ]; then
              echo "update=false" >> $GITHUB_ENV
          else
              echo "update=true" >> $GITHUB_ENV
          fi
      - name: Git merge changes from template to ubluelight/template
        if: ${{ env.update == 'true' }}
        run: git merge template/template --allow-unrelated-histories && git push origin template
      - name: Checkout live
        if: ${{ env.update == 'true' }}
        run: git checkout live
      - name: Git rebase template in live
        if: ${{ env.update == 'true' }}
        run: git rebase --onto origin/template --root live --reapply-cherry-picks && git push origin live -f
