name: template-sync
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout template
        uses: actions/checkout@v4
        with:
          ref: 'template'
      - name: git setup
        run: |
          git config user.name "Vietchinh GitHub Actions Bot"
          git config user.email "1348151+vietchinh@users.noreply.github.com"
      - name: Add ublue-os startingpoint remote
        run: git remote add template https://github.com/ublue-os/startingpoint
      - name: Fetch all
        run: git fetch template
      - name: Merge template
        uses: mtanzi/action-automerge@v1
        id: merge
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source: 'template/template'
          target: 'template'
      - name: Commit & Push changes to master
        uses: benkaiser/rebase-commit-push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          rebase: true
          message: "chore: auto rebase ${date}"
          branch: "live"
          author_email: "1348151+vietchinh@users.noreply.github.com"
          author_name: "vietchinh"